#services:
#  nginx-server:
#    build: ./requirements/nginx
#    image: nginx-server
#    container_name: nginx
#    ports:
#      - "8080:443"

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "8080:443"
    volumes:
      - wp_data:/var/www/html # Shared folder
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html # Shared folder

volumes:
  wp_data: # This creates the shared space
